### ISSUE TITLE
Mention to enable workflows on the fork

### ISSUE THREAD

**Issue by st3iny** [szaimen/did#1]
I followed the instructions from the readme but the action didn't run. It turns out that workflows have to be manually enabled for forks. It can be done by navigating to the `Actions` tab and pressing the green `Enable workflows ...` button.

Could that step be added to the readme?

**Comment by szaimen** [comment]
Thanks for the heads-up! Done with https://github.com/szaimen/did/commit/c1b900a44d3b988adc865239af802e9eb565fc66
